- name: PT3-S1
  types:
    - BS
    - CS
  command: /usr/local/bin/recpt1 --b25 --device /dev/pt3video0 <channel> - -
  decoder: arib-b25-stream-test
  isDisabled: false
- name: PT3-S2
  types:
    - BS
    - CS
  command: /usr/local/bin/recpt1 --b25 --device /dev/pt3video1 <channel> - -
  decoder: arib-b25-stream-test
  isDisabled: false
- name: PT3-T1
  types:
    - GR
  command: /usr/local/bin/recpt1 --b25 --device /dev/pt3video2 <channel> - -
  isDisabled: false
- name: PT3-T2
  types:
    - GR
  command: /usr/local/bin/recpt1 --b25 --device /dev/pt3video3 <channel> - -
  decoder: arib-b25-stream-test
  isDisabled: false
